export function BreezeConnect(params: any): void;
export class BreezeConnect {
    constructor(params: any);
    version: string;
    appKey: any;
    userId: string;
    secretKey: string;
    socket: any;
    socketOrder: any;
    socketOHLCV: any;
    sessionKey: string;
    apiSession: string;
    onTicks: any;
    stockScriptDictList: any[];
    tokenScriptDictList: any[];
    tuxToUserValue: {
        orderFlow: {
            B: string;
            S: string;
            N: string;
        };
        limitMarketFlag: {
            L: string;
            M: string;
            S: string;
        };
        orderType: {
            T: string;
            I: string;
            V: string;
        };
        productType: {
            F: string;
            O: string;
            P: string;
            U: string;
            I: string;
            C: string;
            Y: string;
            B: string;
            M: string;
            T: string;
        };
        orderStatus: {
            A: string;
            R: string;
            Q: string;
            O: string;
            P: string;
            E: string;
            J: string;
            X: string;
            B: string;
            D: string;
            F: string;
            C: string;
        };
        optionType: {
            C: string;
            P: string;
            "*": string;
        };
    };
    socketConnectionResponse: (message: any) => {
        message: any;
    };
    subscribeException: (message: any) => never;
    validationErrorResponse: (message: any) => {
        Success: string;
        Status: number;
        Error: any;
    };
    errorException: (funcName: any, error: any) => never;
    connect: ({ isOrder, isOHLCV }: {
        isOrder?: boolean;
        isOHLCV?: boolean;
    }) => void;
    onDisconnect: () => void;
    generateSession: (secretKey: any, sessionKey: any) => Promise<void>;
    apiUtil: () => Promise<void>;
    watch: (symbols: any) => void;
    watchStrategy: (symbols: any) => void;
    unwatchStrategy: (symbols: any) => void;
    onOhlcStream: (data: any) => void;
    watchStreamData: (symbols: any, channel: any) => void;
    unwatchStreamData: (symbol: any) => void;
    on: (callback: any) => void;
    onMessage: (data: any) => void;
    onMessageStrategy: (data: any) => void;
    notify: () => void;
    unwatch: (symbol: any) => void;
    wsConnectOrder: () => void;
    wsConnect: () => void;
    wsDisconnect: () => void;
    getDataFromStockTokenValue: (inputStockToken: any) => {
        stock_name: any;
        product_type: string;
        strike_date: string;
        strike_price: any;
        right: string;
    };
    getStockTokenValue: ({ exchangeCode, stockCode, productType, expiryDate, strikePrice, right, getExchangeQuotes, getMarketDepth }: {
        exchangeCode?: string;
        stockCode?: string;
        productType?: string;
        expiryDate?: string;
        strikePrice?: string;
        right?: string;
        getExchangeQuotes?: boolean;
        getMarketDepth?: boolean;
    }) => {
        exch_quote_token: boolean;
        market_depth_token: boolean;
    };
    parseOhlcData: (data: any) => {};
    parseMarketDepth: (data: any, exchange: any) => any[];
    parseStrategyData: (data: any) => {
        strategy_date: any;
        modification_date: any;
        portfolio_id: any;
        call_action: any;
        portfolio_name: any;
        exchange_code: any;
        product_type: any;
        underlying: any;
        expiry_date: any;
        option_type: any;
        strike_price: any;
        action: any;
        recommended_price_from: any;
        recommended_price_to: any;
        minimum_lot_quantity: any;
        last_traded_price: any;
        best_bid_price: any;
        best_offer_price: any;
        last_traded_quantity: any;
        target_price: any;
        expected_profit_per_lot: any;
        stop_loss_price: any;
        expected_loss_per_lot: any;
        total_margin: any;
        leg_no: any;
        status: any;
    } | {
        stock_name: any;
        stock_code: any;
        action_type: any;
        expiry_date: any;
        strike_price: any;
        option_type: any;
        stock_description: any;
        recommended_price_and_date: any;
        recommended_price_from: any;
        recommended_price_to: any;
        recommended_date: any;
        target_price: any;
        sltp_price: any;
        part_profit_percentage: any;
        profit_price: any;
        exit_price: any;
        recommended_update: any;
        iclick_status: any;
        subscription_type: any;
    };
    parseData: (data: any) => {
        sourceNumber: any;
        group: any;
        userId: any;
        key: any;
        messageLength: any;
        requestType: any;
        messageSequence: any;
        messageDate: any;
        messageTime: any;
        messageCategory: any;
        messagePriority: any;
        messageType: any;
        orderMatchAccount: any;
        orderExchangeCode: any;
        stockCode: any;
        orderFlow: any;
        limitMarketFlag: any;
        orderType: any;
        orderLimitRate: any;
        productType: any;
        orderStatus: any;
        orderDate: any;
        orderTradeDate: any;
        orderReference: any;
        orderQuantity: any;
        openQuantity: any;
        orderExecutedQuantity: any;
        cancelledQuantity: any;
        expiredQuantity: any;
        orderDisclosedQuantity: any;
        orderStopLossTrigger: any;
        orderSquareFlag: any;
        orderAmountBlocked: any;
        orderPipeId: any;
        channel: any;
        exchangeSegmentCode: any;
        exchangeSegmentSettlement: any;
        segmentDescription: any;
        marginSquareOffMode: any;
        orderValidDate: any;
        orderMessageCharacter: any;
        averageExecutedRate: any;
        orderPriceImprovementFlag: any;
        orderMBCFlag: any;
        orderLimitOffset: any;
        systemPartnerCode: any;
        optionType: any;
        exerciseType: any;
        strikePrice: any;
        expiryDate: any;
        limitRate: any;
        orderTotalQuantity: any;
        executedQuantity: any;
        stopLossTrigger: any;
        specialFlag: any;
        pipeId: any;
        modificationOrCancelFlag: any;
        tradeDate: any;
        acknowledgeNumber: any;
        stopLossOrderReference: any;
        totalAmountBlocked: any;
        cancelFlag: any;
        squareOffMarket: any;
        quickExitFlag: any;
        stopValidTillDateFlag: any;
        priceImprovementFlag: any;
        conversionImprovementFlag: any;
        trailUpdateCondition: any;
    } | {
        Symbol: any;
        AndiOPVolume: any;
        Reserved: any;
        IndexFlag: any;
        ttq: any;
        last: any;
        ltq: any;
        ltt: string;
        AvgTradedPrice: any;
        TotalBuyQnt: any;
        TotalSellQnt: any;
        ReservedStr: any;
        ClosePrice: any;
        OpenPrice: any;
        HighPrice: any;
        LowPrice: any;
        ReservedShort: any;
        CurrOpenInterest: any;
        TotalTrades: any;
        HightestPriceEver: any;
        LowestPriceEver: any;
        TotalTradedValue: any;
        totalBuyQt: any;
        totalSellQ: any;
        ttv: any;
        trend: any;
        lowerCktLm: any;
        upperCktLm: any;
        close: any;
        OI: any;
        CHNGOI: any;
        exchange: string;
    };
    getStockScriptList: () => Promise<void>;
    subscribeFeeds: ({ stockToken, exchangeCode, stockCode, productType, expiryDate, strikePrice, right, getExchangeQuotes, getMarketDepth, getOrderNotification, interval }: {
        stockToken?: string;
        exchangeCode?: string;
        stockCode?: string;
        productType?: string;
        expiryDate?: string;
        strikePrice?: string;
        right?: string;
        getExchangeQuotes?: boolean;
        getMarketDepth?: boolean;
        getOrderNotification?: boolean;
        interval?: string;
    }) => Promise<{}>;
    unsubscribeFeeds: ({ stockToken, exchangeCode, stockCode, productType, expiryDate, strikePrice, right, interval, getExchangeQuotes, getMarketDepth, getOrderNotification }: {
        stockToken?: string;
        exchangeCode?: string;
        stockCode?: string;
        productType?: string;
        expiryDate?: string;
        strikePrice?: string;
        right?: string;
        interval?: string;
        getExchangeQuotes?: boolean;
        getMarketDepth?: boolean;
        getOrderNotification?: boolean;
    }) => Promise<{
        message: any;
    }>;
    generateHeaders: (body: any) => any;
    makeRequest: (method: any, endpoint: any, body: any, header: any) => Promise<any>;
    getCustomerDetails: (session_token?: string) => Promise<any>;
    getDematHoldings: () => Promise<any>;
    getFunds: () => Promise<any>;
    setFunds: ({ transactionType, amount, segment }: {
        transactionType?: string;
        amount?: string;
        segment?: string;
    }) => Promise<any>;
    getHistoricalData: ({ interval, fromDate, toDate, stockCode, exchangeCode, productType, expiryDate, right, strikePrice }: {
        interval?: string;
        fromDate?: string;
        toDate?: string;
        stockCode?: string;
        exchangeCode?: string;
        productType?: string;
        expiryDate?: string;
        right?: string;
        strikePrice?: string;
    }) => Promise<any>;
    getHistoricalDatav2: ({ interval, fromDate, toDate, stockCode, exchangeCode, productType, expiryDate, right, strikePrice }: {
        interval?: string;
        fromDate?: string;
        toDate?: string;
        stockCode?: string;
        exchangeCode?: string;
        productType?: string;
        expiryDate?: string;
        right?: string;
        strikePrice?: string;
    }) => Promise<any>;
    addMargin: ({ productType, stockCode, exchangeCode, settlementId, addAmount, marginAmount, openQuantity, coverQuantity, categoryIndexPerStock, expiryDate, right, contractTag, strikePrice, segmentCode }: {
        productType?: string;
        stockCode?: string;
        exchangeCode?: string;
        settlementId?: string;
        addAmount?: string;
        marginAmount?: string;
        openQuantity?: string;
        coverQuantity?: string;
        categoryIndexPerStock?: string;
        expiryDate?: string;
        right?: string;
        contractTag?: string;
        strikePrice?: string;
        segmentCode?: string;
    }) => Promise<any>;
    getMargin: (exchangeCode?: string) => Promise<any>;
    placeOrder: ({ stockCode, exchangeCode, product, action, orderType, stoploss, quantity, price, validity, validityDate, disclosedQuantity, expiryDate, right, strikePrice, userRemark, orderTypeFresh, orderRateFresh, settlementId, orderSegmentCode }: {
        stockCode?: string;
        exchangeCode?: string;
        product?: string;
        action?: string;
        orderType?: string;
        stoploss?: string;
        quantity?: string;
        price?: string;
        validity?: string;
        validityDate?: string;
        disclosedQuantity?: string;
        expiryDate?: string;
        right?: string;
        strikePrice?: string;
        userRemark?: string;
        orderTypeFresh?: string;
        orderRateFresh?: string;
        settlementId?: string;
        orderSegmentCode?: string;
    }) => Promise<any>;
    getOrderDetail: ({ exchangeCode, orderId }: {
        exchangeCode?: string;
        orderId?: string;
    }) => Promise<any>;
    getOrderList: ({ exchangeCode, fromDate, toDate }: {
        exchangeCode?: string;
        fromDate?: string;
        toDate?: string;
    }) => Promise<any>;
    cancelOrder: ({ exchangeCode, orderId }: {
        exchangeCode?: string;
        orderId?: string;
    }) => Promise<any>;
    modifyOrder: ({ orderId, exchangeCode, orderType, stoploss, quantity, price, validity, disclosedQuantity, validityDate }: {
        orderId?: string;
        exchangeCode?: string;
        orderType?: string;
        stoploss?: string;
        quantity?: string;
        price?: string;
        validity?: string;
        disclosedQuantity?: string;
        validityDate?: string;
    }) => Promise<any>;
    getPortfolioHoldings: ({ exchangeCode, fromDate, toDate, stockCode, portfolioType }: {
        exchangeCode?: string;
        fromDate?: string;
        toDate?: string;
        stockCode?: string;
        portfolioType?: string;
    }) => Promise<any>;
    getPortfolioPositions: () => Promise<any>;
    getQuotes: ({ stockCode, exchangeCode, expiryDate, productType, right, strikePrice }: {
        stockCode?: string;
        exchangeCode?: string;
        expiryDate?: string;
        productType?: string;
        right?: string;
        strikePrice?: string;
    }) => Promise<any>;
    getOptionChainQuotes: ({ stockCode, exchangeCode, expiryDate, productType, right, strikePrice }: {
        stockCode?: string;
        exchangeCode?: string;
        expiryDate?: string;
        productType?: string;
        right?: string;
        strikePrice?: string;
    }) => Promise<any>;
    squareOff: ({ sourceFlag, stockCode, exchangeCode, quantity, price, action, orderType, validity, stoploss, disclosedQuantity, protectionPercentage, settlementId, marginAmount, openQuantity, coverQuantity, productType, expiryDate, right, strikePrice, validityDate, tradePassword, aliasName }: {
        sourceFlag?: string;
        stockCode?: string;
        exchangeCode?: string;
        quantity?: string;
        price?: string;
        action?: string;
        orderType?: string;
        validity?: string;
        stoploss?: string;
        disclosedQuantity?: string;
        protectionPercentage?: string;
        settlementId?: string;
        marginAmount?: string;
        openQuantity?: string;
        coverQuantity?: string;
        productType?: string;
        expiryDate?: string;
        right?: string;
        strikePrice?: string;
        validityDate?: string;
        tradePassword?: string;
        aliasName?: string;
    }) => Promise<any>;
    getTradeList: ({ fromDate, toDate, exchangeCode, productType, action, stockCode }: {
        fromDate?: string;
        toDate?: string;
        exchangeCode?: string;
        productType?: string;
        action?: string;
        stockCode?: string;
    }) => Promise<any>;
    getTradeDetail: ({ exchangeCode, orderId }: {
        exchangeCode?: string;
        orderId?: string;
    }) => Promise<any>;
    previewOrder: ({ stockCode, exchangeCode, productType, orderType, price, action, quantity, expiryDate, right, strikePrice, specialFlag, stoploss, orderRateFresh }: {
        stockCode?: string;
        exchangeCode?: string;
        productType?: string;
        orderType?: string;
        price?: string;
        action?: string;
        quantity?: string;
        expiryDate?: string;
        right?: string;
        strikePrice?: string;
        specialFlag?: string;
        stoploss?: string;
        orderRateFresh?: string;
    }) => Promise<any>;
    limitCalculator: ({ strikePrice, productType, expiryDate, underlying, exchangeCode, orderFlow, stopLossTrigger, optionType, sourceFlag, limitRate, orderReference, availableQuantity, marketType, freshOrderLimit }: {
        strikePrice?: string;
        productType?: string;
        expiryDate?: string;
        underlying?: string;
        exchangeCode?: string;
        orderFlow?: string;
        stopLossTrigger?: string;
        optionType?: string;
        sourceFlag?: string;
        limitRate?: string;
        orderReference?: string;
        availableQuantity?: string;
        marketType?: string;
        freshOrderLimit?: string;
    }) => Promise<any>;
    marginCalculator: ({ payloadList, exchangeCode }: {
        payloadList?: string;
        exchangeCode?: string;
    }) => Promise<any>;
    getNames: ({ exchange, stockCode }: {
        exchange?: string;
        stockCode?: string;
    }) => Promise<Map<string, string> | {
        status: string;
        isec_stock_code: any;
        isec_token: any;
        company_name: any;
        isec_token_level1: string;
        isec_token_level2: string;
        exchange_stockCode: any;
        exchange: string;
    }>;
}
